# Cloudflare Pages configuration for Smokehouse Miami BBQ
# This deploys the frontend only - backend must be hosted separately

name = "smokehouse-miami-bbq"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend/build"

# Environment variables (configure these in Cloudflare Pages dashboard)
# VITE_BACKEND_URL = "https://your-backend-url.com"
