# Cloudflare Pages configuration for frontend only
# Note: This is for Cloudflare Pages, not Workers

name = "smokehouse-miami-bbq"
compatibility_date = "2024-01-01"

# Cloudflare Pages output directory so `wrangler pages deploy` works without args
pages_build_output_dir = "./frontend/build"


# Environment variables for production
[env.production.vars]
# You'll need to host the backend elsewhere and update this URL
# VITE_BACKEND_URL = "https://your-backend-url.com"

# Build configuration
[build]
# Optional: local build command (run manually before deploy)
command = "npm run build"

# Note: FastAPI backend cannot run on Cloudflare Workers
# You'll need to deploy the backend to:
# - Heroku
# - Railway
# - DigitalOcean
# - AWS/Google Cloud/Azure
# - Vercel (for Next.js API routes conversion)
# - Or any traditional hosting platform
